#server:
#  port: 8080
spring:
  application:
    name: edu-api-gateway
  cloud:
    gateway:
      routes:
        - id: edu-content
          uri: lb://edu-content
          predicates:
            - Path=/content/**
          filters:
            - StripPrefix=1
            - name: ContentServiceAccessFilter
              args:
                protectedPaths: /courses
                protectedMethods: GET, POST

        - id: edu-identity
          uri: lb://edu-identity
          predicates:
            - Path=/security/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

netty:
  dns:
    resolver:
      use_native: false
